trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Ejecutando contenedor con la imagen morad02/f1data"
    docker build -t morad02/f1data .
    docker run -tv `pwd`:/app/test morad02/f1data
  displayName: 'Ejecutar contenedor'
