version: v1.0
name: Docker
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
triggers:
  - name: Pull Request and Commits
    event:
      type: pull_request
      branch:
        - '*'
      paths:
        include:
          - src/**
          - test/**
          - dockerfile
blocks:
  - name: Test
    task:
      jobs:
        - name: Build docker and run test
          commands:
            - checkout
            - docker build -t morad02/f1data .
            - 'docker run  -tv `pwd`:/app/test morad02/f1data'
