name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37.2
      - run: deno task test      